run:
  concurrency: 4
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asciicheck
    - bodyclose
    - dogsled
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gci
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - importas
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 35

  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-use-default: false
  exclude-rules:
    - text: "SA1029"
      linters:
        - staticcheck

    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        # bodyclose reports some false-positives when using a test request recorder
        - bodyclose
        # It's overkill to use `NewRequestWithContext` in tests
        - noctx
        - goerr113
        # It's expected to have repeated text appearances in unit tests, and overkill to define constants for those
        - goconst
